import {
  slide1,
  slide2,
  slide3,
  slide4,
  stormProjectPic1,
  stormProjectPic2,
  stormProjectPic3,
  stormProjectPic4,
  stormProjectPic5,
  stormProjectPic6,
  stormProjectPic7,
  stormProjectPic8,
  stormProjectPic9,
  stormProjectPic10,
  stormProjectPic11,
  stormProjectPic12,
  BIOXProjectPic1,
  BIOXProjectPic2,
  BIOXProjectPic3,
  BIOXProjectPic4,
  BIOXProjectPic5,
  BIOXProjectPic6,
  BIOXProjectPic7,
  GabionProject1,
  GabionProject2,
  GabionProject3,
  GabionProject4,
  GabionProject5,
  GabionProject6,
  GabionProject7,
  GabionProject8,
  GabionProject9,
  GabionProject10,
  GabionProject11,
  GabionProject12,
  GabionProject13,
  GabionProject14,
  GabionProject15,
  GabionProject16,
  GabionProject17,
  GabionProject18,
  GabionProject19,
  GabionProject20,
  GabionProject21,
  GabionProject22,
  GabionProject23,
  GabionProject24,
  GabionProject25,
  GabionProject26,
  GabionProject27,
  GabionProject28,
  GabionProject29,
  GabionProject30,
  GabionProject31,
  GabionProject32,
  GabionProject33,
  GabionProject34,
  GabionProject35,
  GabionProject36,
  GabionProject37,
  GabionProject38,
  GabionProject39,
  GabionProject40,
  GabionProject41,
  GabionProject42,
  GabionProject43,
  GabionProject44,
  collapseProject1,
  collapseProject2,
  collapseProject3,
  collapseProject4,
  collapseProject5,
  collapseProject6,
  collapseProject7,
  collapseProject8,
  collapseProject9,
  collapseProject10,
  collapseProject11,
  collapseProject12,
  collapseProject13,
  collapseProject14,
  collapseProject15,
  collapseProject16,
  collapseProject17,
  collapseProject18,
  collapseProject19,
  collapseProject20,
  collapseProject21,
  collapseProject22,
  collapseProject23,
  collapseProject24,
  collapseProject25,
  collapseProject26,
  collapseProject27,
  collapseProject28,
  collapseProject29,
} from "../../assets/images";

// Offer items is not a part of them
export const offerItems = [
  {
    id: 1,
    title: "Mineral Production",
    description:
      "We explore, develop, and produce various minerals at mines all over the world.",
    image: slide1,
  },
  {
    id: 2,
    title: "Sustainable Mining",
    description:
      "Our practices focus on environmental responsibility and community engagement.",
    image: slide4,
  },
  {
    id: 3,
    title: "Expert Consultation",
    description:
      "We provide expert advice on mining operations and resource management.",
    image: slide2,
  },
  {
    id: 4,
    title: "Advanced Equipment",
    description:
      "We utilize state-of-the-art machinery for efficient and safe mining operations.",
    image: slide3,
  },
  {
    id: 5,
    title: "Modern Technology",
    description:
      "Our company uses top-notch technology to make mining safer and more productive.",
    image: slide4,
  },
  {
    id: 6,
    title: "Safety Training",
    description:
      "We offer safety training programs to ensure the well-being of our employees.",
    image: slide1,
  },
];

export const projects = [
  {
    id: 1,
    title: "The Storm Water Project",
    location: "GHANA",
    description:
      "The Storm Water Project shown in the second image focuses on infrastructure to manage stormwater, mitigating flooding and controlling water flow in urban or rural areas. This involves constructing channels, reinforced concrete structures, and drainage systems to handle heavy rains. The picture shows workers installing reinforced formwork, which will eventually direct water flow, preventing erosion and protecting nearby communities from water damage.",
    image:
      "https://images.prismic.io/ramoth-company/ZzPo7K8jQArT0yKc_storm-project-pic-1.jpg?auto=format,compress",
    images: [
      stormProjectPic1,
      stormProjectPic2,
      stormProjectPic3,
      stormProjectPic4,
      stormProjectPic5,
      stormProjectPic6,
      stormProjectPic7,
      stormProjectPic8,
      stormProjectPic9,
      stormProjectPic10,
      stormProjectPic11,
      stormProjectPic12,
    ],
    category: "Projects",
  },
  {
    id: 2,
    title: "The BIOX TSF Project",
    location: "GHANA",
    description:
      "The BIOX TSF project involves constructing a Tailings Storage Facility (TSF), a specially designed containment system for managing mine waste (tailings) from a biological oxidation (BIOX) process. The images show extensive earthworks, including leveling, excavation, and liner placement, essential to prevent environmental contamination. TSFs are critical for the safe disposal of toxic byproducts from mining, protecting surrounding ecosystems from hazardous materials. The site preparation appears advanced, with attention to drainage and environmental safeguards.",
    image:
      "https://images.prismic.io/ramoth-company/ZzPmwa8jQArT0yKH_project-pic-1.jpg?auto=format,compress",
    category: "Projects",
    images: [
      BIOXProjectPic1,
      BIOXProjectPic2,
      BIOXProjectPic3,
      BIOXProjectPic4,
      BIOXProjectPic5,
      BIOXProjectPic6,
      BIOXProjectPic7,
    ],
  },
  {
    id: 3,
    title: "Gabion Basket Project",
    location: "GHANA",
    description:
      "Gabion Basket Project involves the use of rectangular or cylindrical wire mesh containers, commonly filled with stones, to create durable and visually appealing structures. These projects are widely implemented in civil engineering, landscaping, and architectural design due to their strength, eco-friendliness, and versatility..",
    image:
      "https://images.prismic.io/ramoth-company/Z0Rp8K8jQArT1RR1_Project-25.jpg?auto=format,compress",
    category: "Projects",
    images: [
      GabionProject1,
      GabionProject2,
      GabionProject3,
      GabionProject4,
      GabionProject5,
      GabionProject6,
      GabionProject7,
      GabionProject8,
      GabionProject9,
      GabionProject10,
      GabionProject11,
      GabionProject12,
      GabionProject13,
      GabionProject14,
      GabionProject15,
      GabionProject16,
      GabionProject17,
      GabionProject18,
      GabionProject19,
      GabionProject20,
      GabionProject21,
      GabionProject22,
      GabionProject23,
      GabionProject24,
      GabionProject25,
      GabionProject26,
      GabionProject27,
      GabionProject28,
      GabionProject29,
      GabionProject30,
      GabionProject31,
      GabionProject32,
      GabionProject33,
      GabionProject34,
      GabionProject35,
      GabionProject36,
      GabionProject37,
      GabionProject38,
      GabionProject39,
      GabionProject40,
      GabionProject41,
      GabionProject42,
      GabionProject43,
      GabionProject44,
    ],
  },
  {
    id: 4,
    title:
      "Collapsed Wall Stabilisation and Upstream Embarkment Wall Raise Project",
    location: "GHANA",
    description:
      "A Collapsed Wall Stabilization Project focuses on repairing and reinforcing a previously failed or damaged wall structure to restore its stability and functionality. This type of project is critical in areas where structural integrity has been compromised due to erosion, weathering, natural disasters, or excessive loading.",
    image:
      "https://images.prismic.io/ramoth-company/Z0RqCK8jQArT1RSK_Project-44.jpg?auto=format,compress",
    category: "Projects",
    images: [
      collapseProject1,
      collapseProject2,
      collapseProject3,
      collapseProject4,
      collapseProject5,
      collapseProject6,
      collapseProject7,
      collapseProject8,
      collapseProject9,
      collapseProject10,
      collapseProject11,
      collapseProject12,
      collapseProject13,
      collapseProject14,
      collapseProject15,
      collapseProject16,
      collapseProject17,
      collapseProject18,
      collapseProject19,
      collapseProject20,
      collapseProject21,
      collapseProject22,
      collapseProject23,
      collapseProject24,
      collapseProject25,
      collapseProject26,
      collapseProject27,
      collapseProject28,
      collapseProject29,
    ],
  },
];

export const services = [
  {
    id: 1,
    title: "Mining of Tailings Materials",
    description:
      "Mining of tailings materials involves the reprocessing of previously discarded mine waste to extract valuable minerals that were not recovered during the initial processing. This service leverages advancements in technology to recover metals, reduce waste, and minimize environmental impact.",
    image:
      "https://images.prismic.io/ramoth-company/Zw8NFIF3NbkBXe8Z_dominik-vanyi-Mk2ls9UBO2E-unsplash.jpg?auto=format,compress",
    category: "Services",
  },
  {
    id: 2,
    title: "Construction of Tailings Dams",
    description:
      "Tailings dams are structures used to store mining waste materials, known as tailings. Their construction is crucial for containing hazardous materials, ensuring environmental safety, and preventing water contamination. Proper design and monitoring are essential to avoid failures and protect nearby ecosystems.",
    image:
      "https://images.prismic.io/ramoth-company/Zw8AE4F3NbkBXe5U_john-gibbons-E2TVn-NpCU4-unsplash.jpg?auto=format,compress",
    category: "Services",
  },
  {
    id: 3,
    title: "Construction of Mine Haul Roads",
    description:
      "The construction of mine haul roads involves creating durable, high-capacity roads that allow heavy machinery to transport ore, waste, and equipment within mining sites. These roads are designed for stability, minimal maintenance, and to support the intense loads imposed by mining vehicles.",
    category: "Services",
    image:
      "https://images.prismic.io/ramoth-company/ZxY67oF3NbkBXw9G_MineHaul.png?auto=format,compress",
  },
  {
    id: 4,
    title: "Lease of Earthmoving Equipment",
    description:
      "Leasing earthmoving equipment allows businesses to access essential machinery for construction, mining, and excavation without committing to a full purchase. This service offers flexibility and affordability, enabling companies to acquire the right tools for temporary projects or short-term needs while preserving capital.",
    image:
      "https://images.prismic.io/ramoth-company/ZxZEXoF3NbkBXxCq_Lease.jpg?auto=format,compress",
    category: "Services",
  },
  {
    id: 5,
    title: "Maintenance of Earth Moving Equipment",
    description:
      "The maintenance of earthmoving equipment involves regular inspections, servicing, and repairs to ensure machinery remains in optimal working condition. Proper maintenance minimizes equipment downtime, extends lifespan, and ensures safety during heavy-duty operations in mining, construction, and excavation projects.",
    category: "Services",
    image:
      "https://images.prismic.io/ramoth-company/ZxZEYIF3NbkBXxCt_mainte02.png?auto=format,compress",
  },
  {
    id: 6,
    title: "Haulage of Ore",
    description:
      "The haulage of ore involves the transportation of extracted minerals from the mining site to processing facilities or storage areas. This service requires specialized vehicles capable of carrying heavy loads over long distances, ensuring the safe and efficient movement of ore for further processing.",
    category: "Services",
    image:
      "https://images.prismic.io/ramoth-company/ZxZFFoF3NbkBXxDv_orehauage.jpg?auto=format,compress",
  },
  {
    id: 7,
    title: "Backfilling of Mined Out Pits",
    description:
      "The backfilling of mined-out pits involves refilling areas that have been excavated during mining operations. This process helps stabilize the landscape, minimize environmental impact, and prepare the site for rehabilitation or future land use. It is a crucial part of mine closure and sustainability efforts.",
    category: "Services",
    image:
      "https://images.prismic.io/ramoth-company/ZxZJSoF3NbkBXxHC_backfilling.jpg?auto=format,compress",
  },
  {
    id: 8,
    title: "Maintenance and Repair of Tailings Dams",
    description:
      "This service involves the regular inspection, monitoring, and repair of tailings dams to ensure their structural integrity and prevent potential environmental hazards. Maintenance activities focus on controlling erosion, preventing seepage, and repairing any detected weaknesses.",
    category: "Services",
    image: slide4,
  },
];
